# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: A lazy approach to Machine Learning
description: Learning Data Science and Improving every day!!
url: https://bluzeey.github.io
avatar: /avatar.jpeg
paginate: 5
cover_image: ![image](https://user-images.githubusercontent.com/64553800/96010171-23309300-0e5f-11eb-96db-d4f200928a53.png)
github_username: bluzeey

# Email and twitter are optional:
email: sahilm1711@gmail.com 
twitter_username:

# Set this to true to get LaTeX math equation support
use_math: true

# Add your Google Analytics ID here if you have one and want to use it
google_analytics:

theme: jekyll-theme-midnight
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
